baseURL = "https://theoppositeof.cool/"
#baseURL = "https://edyesed.github.io/"
languageCode = "en-us"
title = "the opposite of cool"
theme = "beautifulhugo"
copyright = "(c) 2018 <a href='https://twitter.com/edyesed'>@edyesed</a>"
metaDataFormat = "yaml"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
googleAnalytics = "UA-50727013-2"
disqusShortname = "https-theoppositeof-cool"

pluralizelisttitles = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# 3 color palatte http://paletton.com/#uid=32N0I0kjcl79tv1expBndh1sBbN
# 4 color palatte http://paletton.com/#uid=7290s0kllllaFw0g0qFqFg0w0aF
#[permalinks]
##    articles = "/:year/:month/:day/:slug/"
##    blog = "/:year/:month/:day/:slug/"
##    posts = "/:year/:month/:day/:slug/"
##    tutorials = "/:slug/"
##    code = "/:slug/"
##
##[author]
##    name = "ed"
##    email = "ed@theoppositeof.cool"
##
[Params]
  homeTitle = ' '
  subtitle = "yay, another atrophying blog"
  logo = "img/avatar-icon.gif"
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true

[Author]
  name = "Ed"
  github = "edyesed/" # Your Github profile ID
  linkedin = "edyesed" # Your LinkedIn profile ID (from public URL)
  twitter = "edyesed" # Your Twitter profile ID

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    identifier = "tech"
    url = "tech/"
    name = "Tech"
    weight = 2
#
#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1
#
#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3
