baseURL = "https://theoppositeof.cool/"
languageCode = "en-us"
title = "the opposite of cool"
theme = "hugo-theme-dopetrope"
copyright = "(c) 2018 <a href='https://twitter.com/edyesed'>@edyesed</a>"
metaDataFormat = "yaml"
# 3 color palatte http://paletton.com/#uid=32N0I0kjcl79tv1expBndh1sBbN
# 4 color palatte http://paletton.com/#uid=7290s0kllllaFw0g0qFqFg0w0aF
#[permalinks]
##    articles = "/:year/:month/:day/:slug/"
##    blog = "/:year/:month/:day/:slug/"
##    posts = "/:year/:month/:day/:slug/"
##    tutorials = "/:slug/"
##    code = "/:slug/"
##
##[taxonomies]
##    tag = "tags"
##    topic = "topics"
##
##[author]
##    name = "ed"
##    email = "ed@theoppositeof.cool"
##
[params.portfolio]
    # You can use markdown here.
    title = "tech"
    foldername = "tech"
    findoutmoretext = "read about this"

[params.blog]
    title = "blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    # Google Analytics.
    googleAnalytics = "UA-50727013-2"
    disqus = "https-theoppositeof-cool"

##    # Sidebar social links.
##    github = "edyesed/" # Your Github profile ID
##    linkedin = "edyesed" # Your LinkedIn profile ID (from public URL)
##    twitter = "edyesed" # Your Twitter profile ID
##    #youtube = ""   Your Youtube channel ID
##    #flattr = ""  # populate with your flattr uid
##    #flickr = "" # Your Flickr profile ID
##    #vimeo = "" # Your Vimeo profile ID
##
##    # Sidebar RSS link: will only show up if there is a RSS feed
##    # associated with the current page
##    rss = true

